version: '2'

services:
    mysql_db:
        image: mysql
        container_name: 'mysql'
        ports:
          - '3306:3306'
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
          MYSQL_USER: root
          MYSQL_PASSWORD: root
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake

    redis_db:
        image: redis
        container_name: 'redis'
        ports:
          - '6379:6379'

    app:
        build: .
        container_name: 'spring-app'
        depends_on:
          - mysql_db
          - redis_db
        ports:
          - '8080:8080'
        volumes:
          - .:/spring-boot-bestpractice
