version: '2'

services:
    mysql_db:
        image: mysql
        ports:
          - '3306:3306'
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
          MYSQL_USER: root
          MYSQL_PASSWORD: root
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake

    app:
        build: .
        depends_on:
          - mysql_db
        ports:
          - '8080:8080'
        volumes:
          - .:/spring-boot-bestpractice
        environment:
          MYSQL_DB_HOST: mysql_db
          MYSQL_DB_NAME: test
          MYSQL_DB_USER: root
          MYSQL_DB_PASS: root

# mysql -h 127.0.0.1 -u root -p < sql/mysql_sample.sql