version: '2'

services:
    db:
        image: mysql
        ports:
          - '3306:3306'
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
          MYSQL_USER: root
          MYSQL_PASSWORD: root

    app:
        build: .
        depends_on:
          - db
        ports:
          - '8080:8080'
        volumes:
          - .:/spring-boot-bestpractice
        environment:
          DB_HOST: db
          DB_NAME: test
          DB_USER: root
          DB_PASS: root
#        command: mysql -h 127.0.0.1 -u root -p <  sql/sample.sql
