version: '2'

services:
    db:
        image: mysql
        ports:
          - '3306:3306'
        hostname: localhost
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: adocs_db
          MYSQL_USER: root
          MYSQL_PASSWORD: root

    app:
        build: .
        depends_on:
            - db
        ports:
            - '8080:8080'
        volumes:
            - .:/app