# MySQL info
mysql:
  url:  jdbc:mysql://locahost:3306/test
  username: test
  password: test
  driverClassName: com.mysql.jdbc.Driver

# PostgresSQL info
postgres:
  url:  jdbc:postgresql://localhost/test
  username: test
  password: test
  driverClassName: org.postgresql.Driver

# MongoDB info
mongo:
  host: localhost
  port: 27017
  url: mongodb://localhost/test
  database: test
  username: test
  password: test

# Cassandra info
cassandra:
  hosts:
    - test
    - test
    - test
  username: test
  password: test