# Heroku postgres
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    tomcat:
      max-active: 10
      max-idle: 5
      min-idle: 2
      initial-size: 5
      remove-abandoned: true
  jackson:
    property-naming-strategy: SNAKE_CASE
