spring:
  profiles:
    active: loc
  datasource:
    url: jdbc:mysql://${MYSQL_DB_HOST}:3306/${MYSQL_DB_NAME}?useSSL=false
    username: ${MYSQL_DB_USER}
    password: ${MYSQL_DB_PASS}
    driver-class-name: com.mysql.jdbc.Driver

## MongoDB info
#mongo:
#  host: localhost
#  port: 27017
#  url: mongodb://localhost/test
#  database: test
#  username: test
#  password: test
#
## Cassandra info
#cassandra:
#  hosts:
#    - test
#    - test
#    - test
#  username: test
#  password: test