# MySQL info
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.jdbc.Driver

## PostgresSQL info
#postgres:
#  url:  jdbc:postgresql://localhost/test
#  username: test
#  password: test
#  driverClassName: org.postgresql.Driver
#
## MongoDB info
#mongo:
#  host: localhost
#  port: 27017
#  url: mongodb://localhost/test
#  database: test
#  username: test
#  password: test
#
## Cassandra info
#cassandra:
#  hosts:
#    - test
#    - test
#    - test
#  username: test
#  password: test