resources:
  - name: repository
    type: git
    source:
      branch: master
      uri: git@github.com:tomo0111/springboot-bestpractice.git
      private_key: ((github-deploy-key))

  - name: pull-request
    type: pull-request
    source:
      uri: git@github.com:tomo0111/springboot-bestpractice.git
      repo: tomo0111/springboot-bestpractice
      access_token: ((github-access-token))
      private_key: ((github-deploy-key))
      base: master

  - name: springboot-bestpractice-image
    type: docker-image
    source:
      repository: ((docker-hub-account))/springboot-bestpractice
      username: ((docker-hub-user))
      password: ((docker-hub-pass))

resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: jtarchie/pr

  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

jobs:
  - name: unit-test
    serial: true
    public: true
    plan:
    - get: repository
      resource: pull-request
      trigger: true
      version: every
    - do:
      - put: pull-request
        params:
          path: repository
          status: pending
      - task: unit-test
        file: repository/concourse/unit-test.yml
      on_success:
        put: pull-request
        params:
          path: repository
          status: success
      on_failure:
        put: pull-request
        params:
          path: repository
          status: failure

  - name: deploy-image
    serial: true
    public: true
    plan:
    - get: repository
      trigger: true
    - do:
      - task: unit-test
        file: repository/concourse/unit-test.yml
      - task: deploy-image
        file: repository/concourse/deploy-image.yml
      - put: springboot-bestpractice-image
        params:
          tag:
          build: repository