resources:
  - name: repository
    type: git
    source:
      branch: master
      uri: git@github.com:tomo0111/springboot-bestpractice.git
      private_key: ((github-deploy-key))

jobs:
- name: unit-test
  public: true
  plan:
  - get: repository
    trigger: true
  - task: unit-test
    file: repository/concourse/unit-test.yml