resources:
  - name: repository
    type: git
    source:
      uri: git@github.com:tomo0111/springboot-bestpractice.git
      branch: master
      private_key: ((github-private-key))

jobs:
- name: unit-test
  public: true
  plan:
  - get: repository
    trigger: true
  - task: unit-test
    file: concoure/unit-test.yml