resources:
  - name: repo
    type: git
    source:
      branch: master
      uri: git@github.com:tomo0111/springboot-bestpractice.git
      private_key: ((github-private-key))

jobs:
- name: unit-test
  public: true
  plan:
  - get: repo
    trigger: true
  - task: unit-test
    file: repo/concourse/unit-test.yml